"""rename_enum_types_and_add_nextofkin

Revision ID: c044166b6db7
Revises: c9d1868f8514
Create Date: 2025-11-24 00:17:08.311245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c044166b6db7'
down_revision: Union[str, None] = 'c9d1868f8514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nextofkin',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('relationship', sa.Enum('Parent', 'Sibling', 'Spouse', 'Child', 'Other', name='relationshiptypeenum'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('passport_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('profile', 'title',
               existing_type=postgresql.ENUM('Mr', 'Mrs', 'Miss', name='salutationschema'),
               type_=sa.Enum('Mr', 'Mrs', 'Miss', name='salutationenum'),
               existing_nullable=False)
    op.alter_column('profile', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Other', name='genderschema'),
               type_=sa.Enum('Male', 'Female', 'Other', name='genderenum'),
               existing_nullable=False)
    op.alter_column('profile', 'marital_status',
               existing_type=postgresql.ENUM('Single', 'Married', 'Divorced', 'Widowed', name='maritalstatusschema'),
               type_=sa.Enum('Single', 'Married', 'Divorced', 'Widowed', name='maritalstatusenum'),
               existing_nullable=False)
    op.alter_column('profile', 'means_of_identification',
               existing_type=postgresql.ENUM('Passport', 'NationalID', 'DriverLicense', name='identificationtypeschema'),
               type_=sa.Enum('Passport', 'NationalID', 'DriverLicense', name='identificationtypeenum'),
               existing_nullable=False)
    op.alter_column('profile', 'employment_status',
               existing_type=postgresql.ENUM('Employed', 'SelfEmployed', 'Unemployed', 'Student', 'Retired', name='employmentstatusschema'),
               type_=sa.Enum('Employed', 'SelfEmployed', 'Unemployed', 'Student', 'Retired', name='employmentstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'employment_status',
               existing_type=sa.Enum('Employed', 'SelfEmployed', 'Unemployed', 'Student', 'Retired', name='employmentstatusenum'),
               type_=postgresql.ENUM('Employed', 'SelfEmployed', 'Unemployed', 'Student', 'Retired', name='employmentstatusschema'),
               existing_nullable=False)
    op.alter_column('profile', 'means_of_identification',
               existing_type=sa.Enum('Passport', 'NationalID', 'DriverLicense', name='identificationtypeenum'),
               type_=postgresql.ENUM('Passport', 'NationalID', 'DriverLicense', name='identificationtypeschema'),
               existing_nullable=False)
    op.alter_column('profile', 'marital_status',
               existing_type=sa.Enum('Single', 'Married', 'Divorced', 'Widowed', name='maritalstatusenum'),
               type_=postgresql.ENUM('Single', 'Married', 'Divorced', 'Widowed', name='maritalstatusschema'),
               existing_nullable=False)
    op.alter_column('profile', 'gender',
               existing_type=sa.Enum('Male', 'Female', 'Other', name='genderenum'),
               type_=postgresql.ENUM('Male', 'Female', 'Other', name='genderschema'),
               existing_nullable=False)
    op.alter_column('profile', 'title',
               existing_type=sa.Enum('Mr', 'Mrs', 'Miss', name='salutationenum'),
               type_=postgresql.ENUM('Mr', 'Mrs', 'Miss', name='salutationschema'),
               existing_nullable=False)
    op.drop_table('nextofkin')
    # ### end Alembic commands ###
