"""add_profile_table

Revision ID: c9d1868f8514
Revises: 7e1799408eb1
Create Date: 2025-11-16 22:50:23.643189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9d1868f8514'
down_revision: Union[str, None] = '7e1799408eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('title', sa.Enum('Mr', 'Mrs', 'Miss', name='salutationenum'), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='genderenum'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('country_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marital_status', sa.Enum('Single', 'Married', 'Divorced', 'Widowed', name='maritalstatusenum'), nullable=False),
    sa.Column('means_of_identification', sa.Enum('Passport', 'NationalID', 'DriverLicense', name='identificationtypeenum'), nullable=False),
    sa.Column('id_issue_date', sa.Date(), nullable=False),
    sa.Column('id_expiry_date', sa.Date(), nullable=False),
    sa.Column('passport_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employment_status', sa.Enum('Employed', 'SelfEmployed', 'Unemployed', 'Student', 'Retired', name='employmentstatusenum'), nullable=False),
    sa.Column('employer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employer_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employer_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employer_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('annual_income', sa.Float(), nullable=False),
    sa.Column('date_of_employment', sa.Date(), nullable=False),
    sa.Column('profile_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
