"""add_name_on_card_to_virtual_card

Revision ID: cebd8255d7e9
Revises: e37880082002
Create Date: 2025-12-09 11:59:22.419135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cebd8255d7e9'
down_revision: Union[str, None] = 'e37880082002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtualcard', sa.Column('name_on_card', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtualcard', 'name_on_card')
    # ### end Alembic commands ###
